<?php



function drupalmodule_block_info() {
	 $blocks ['helloworld'] = array(
	 	 'info' => t('Hello World!'),
		 'cache' => DRUPAL_CACHE_PER_ROLE,
		 );
		 
	return $blocks;
}

function drupalmodule_block_view($delta) {
	 $block = array();

	 switch ($delta){
	 	case 'helloworld':
		     $block['subject'] = t('Hello');
		     $block['content'] = t('Hello World!');
		     break;
	        default:
		     break;
	}
       return $block;
} 
	 	