<?php



function drupalmodule_block_info() {
	 $blocks ['quoterotator'] = array(
	 	 'info' => t('Quote Rotator'),
		 'cache' => DRUPAL_CACHE_PER_ROLE,
		 );
		 
	return $blocks;
}

function drupalmodule_block_view($delta) {
	 $block = array();

	 switch ($delta){
	 	case 'quoterotator':
		     $block['subject'] = t('Quote of the Day');
		     $block['content'] = t('Hello World!');
		     break;
	        default:
		     break;
	}
       return $block;
}

function drupalmodule_block_configure($delta) {
	$form = array();
	$form['quote1'] = array(
	'#type' => 'text',
	'#quote1_text' => t('Quote 1'),
	'#quote1_attribution' => t('Attribution 1')
	'#default_value' = t('Quote goes here.')
);
return $form;
}

	 	
