<?php



function drupalmodule_block_info() {
	 $blocks ['helloworld'] = array(
	 	 'info' => t('Hello World!'),
		 'cache' => DRUPAL_CACHE_PER_ROLE,
		 );
		 
	return $blocks;
}

function drupalmodule_block_view($delta = '') {
	 $block = array();

	 switch ($delta){
	 	case 'Hello':
		     $block['subject'] = t('Hello');
		     $block['content'] = array(
		     		       '#title' => t('Hello World!'),);
	break;

	else{
	$block['content'] = t('No content available.');
}
break;
}
return $block;
} 
	 	